### ISSUE TITLE
Add "Categories" table and category FK in surveys table

### ISSUE THREAD

**Issue by kaedub** [libellis/libellis-api#9]
The data model needs an update. The surveys table needs to have a "group" or "category" column. This is a good time to come up with a systematic and agreed upon way to handle data migrations.

**Comment by PrismaPhonic** [comment]
On the migrations note I would vote for handling migrations with diesel.  You don't have to know any rust at all for the migrations part.  Just use the terminal client (3 commands you need to know) and know how to write raw SQL.  that's all that's involved.  I can embed the diesel migrations in the birdseed app (already done actually) and you can run migrations easily with $ birdseed migration - or if you'd rather you can run  with using the diesel terminal application

**Comment by PrismaPhonic** [comment]
Either way I'm going to actively keep migrations working on birdseed which already relies on diesel for everything.  If we came up with a secondary migration system then it would be work in two places for me lol
